### PR TITLE
Add example config file

### PR DESCRIPTION
**Pull request by joshbwlng**
Change-type: patch
Signed-off-by: Josh Bowling <josh@monarci.com>

---

Add `example.yml` file for https://github.com/product-os/flowzonify to reference

### CODE REVIEW

**Comment by ab77** [comment]
@joshbwlng this would need to be synced up with the README.md (which already has this information). Do we add a lot of value by placing another file in there to keep in sync with the README manually? cc @klutchell

**Comment by klutchell** [comment]
I agree with Anton that this is duplicating the information we would have to keep up-to-date. If we want an example file we should link to it from the README to avoid having the info in two places.

However I think what we have on the README is good enough?

**Comment by ab77** [comment]
@joshbwlng I'll close this for now, if there is a strong reason for a separate file in the future, let's re-open then.

**Comment by joshbwlng** [comment]
@klutchell @ab77 I had the same thought about it duplicating data before opening the PR (why I didn't merge it myself btw). The idea here is to enable flowzonify with https://github.com/product-os/flowzonify/pull/9 to be able to automatically open PRs on repos to update their flowzone config when necessary (think renovate/dependabot but for flowzone configs). For example to automatically open PRs to enable external contributions for our public repos, instead of having to do it manually. After thinking about it a bit more, I think it could also make sense to keep the reference in the flowzonify repo. This means we would need to manually update the reference in that repo, but it could then open all other PRs for us, much better than what we have now at least.

I had thought about moving the examples out of the flowzone readme into yaml files and then referencing them from the readme, but as an end-user I much prefer making examples like that immediately visible and available in the main readme. :thinking:

**Pull request closed without merging**
