### PR TITLE
Add example of configuring input to usage

### PR DESCRIPTION
**Pull request by anujdeshpande**
Change-type: patch

### CODE REVIEW

**Comment by anujdeshpande** [comment]
@klutchell I am wondering how did this PR get merged without any review? It adds a documentation change, but my trusty windows machine changed the whitespaces to space instead of tabs or something. So it looks ugly 

I don't mind opening a new PR to fix it, but I am afraid it will merge without review again!

image

**Comment by klutchell** [comment]
@anujdeshpande I fixed the whitespace for you. The PR auto merged because we had approvals set to 0 on this repo until [just now](https://github.com/product-os/flowzone/pull/122).

**Comment by anujdeshpande** [comment]
@klutchell oh cool! Thanks!

Is this something that we'll have to do for the repos that use flowzone as well?

**Comment by klutchell** [comment]
> @klutchell oh cool! Thanks!
> 
> Is this something that we'll have to do for the repos that use flowzone as well?

No, the [default](https://github.com/product-os/flowzone#required_approving_review_count) is 1.

**Pull request merged**
