### PR TITLE
Output Cloudflare Deployment URL 

### PR DESCRIPTION
**Pull request by vipulgupta2048**
My usecase for this output is to get it from Flowzone and give it to the link checker running in Docs to check links for the staging docs in order to make sure we are not breaking links on a per PR basis. 
(Pain driven development: I broke a link on a previous PR and link-checker didn't find out)

Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>

### CODE REVIEW

**Comment by klutchell** [comment]
How is link-checker going to get this output? Outputs are not shared between workflows.

**Comment by vipulgupta2048** [comment]
@klutchell  Plan is to bring the link-checker as Job2 in the flowzone.yml workflow file when this PR gets merged.

**Comment by ab77** [comment]
> @klutchell Plan is to bring the link-checker as Job2 in the flowzone.yml workflow file when this PR gets merged. Get the output that way from job 1, which is flowzone

So have you tested if the following works in your downstream repo(s) @vipulgupta2048?

```
jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@vipulgupta2048/output-cf
    outputs:
      cloudflare_deployment_url: ${{ steps.website_publish.outputs. cloudflare_deployment_url }}
    ...

  link-check:
    uses: ./.github/workflows/foo.yml
    needs: [flowzone]
    with:
      bar: needs.jobs.flowzone.outputs.cloudflare_deployment_url
```

**Comment by klutchell** [comment]
Looks fine to me and relatively harmless. You can remove your test commit and rebase.

**Review by klutchell — APPROVED** [review]

**Pull request merged**
