### PR TITLE
Enable docusaurus website build by default

### PR DESCRIPTION
**Pull request by klutchell**
Change-type: patch
Signed-off-by: Kyle Harding <kyle@balena.io>

### CODE REVIEW

**Comment by klutchell** [comment]
@balena-ci I self-certify!

**Comment by vipulgupta2048** [comment]
I don't know if we do want any builds running until they have `cloudflare_website` input set

**Comment by klutchell** [comment]
> I don't know if we do want any builds running until they have `cloudflare_website` input set

`cloudflare_website` is still required as per
https://github.com/product-os/flowzone/blob/5db785a6485d6f163f813dc5767179eb9b6eced6/flowzone.yml#L1617

But I missed this on your original PR, we want to default to docusaurus, not custom build script. Your PR actually failed the e2e test because this repo is configured for docusaurus but we accidentally defaulted to false.

**Comment by vipulgupta2048** [comment]
The `docusaurus_website` being true and false is an implementation detail only valid for one repository atm. Can you refer to what does `default: true` does in GitHub actions

**Comment by klutchell** [comment]
If you don't provide that input when calling Flowzone, it will default to
true. This is what we want because before your PR that input didn't exist
and docusaurus was assumed true in all cases.

Now we have that input so repos with custom docs builds can manually set
docusaurus_website to false.

**Comment by vipulgupta2048** [comment]
Yeah, I edited the message a bit once I looked at the commit more closely. I will open a followup PR to fix the README

**Pull request merged**
