### PR TITLE
Re-enable self-tests on armv7 and x86 self-hosted runners

### PR DESCRIPTION
**Pull request by klutchell**

### CODE REVIEW

**Comment by klutchell** [comment]
> @klutchell the invariant tag is called `X64`, not `amd64`.

We are specifically looking for `platform:linux/amd64` which is added at build time. We don't need to use the GitHub automatic labels.

**Comment by ab77** [comment]
@klutchell found it: https://github.com/organizations/balena-io/settings/actions/runner-groups/3

image

**Comment by ab77** [comment]
@klutchell shod be good to go [now](https://github.com/product-os/flowzone/actions/runs/4419442080/jobs/7751496810#step:1:2)

The agents were failing self updates due to home directory permissions.

**Comment by klutchell** [comment]
I self-certify!

**Pull request merged**
