### PR TITLE
Enable publishing/finalizing docker images without docker-compose tests

### PR DESCRIPTION
**Pull request by Page-**
Change-type: minor

### CODE REVIEW

**Comment by klutchell** [comment]
Why would we allow publishing without tests? Even just a dummy test would
be worth adding to any repo that's missing one.

**Comment by Page-** [comment]
@klutchell part of the problem is I don't know how I'd even add a dummy test that doesn't actually do anything. That said the primary reason is to allow parity with balenaCI for repos where they had balenaCI publishing but still used eg circleCI testing so it's not that they don't have tests but rather that those tests are not expected to be run via flowzone (yet)

**Comment by Page-** [comment]
Also the other issue is that the repos were already converted to flowzone and I only realized when I went to deploy and the artifacts weren't there

**Comment by Page-** [comment]
@klutchell I added a warning if tests aren't being used to encourage the use of tests but not enforce it for the moment

**Comment by Page-** [comment]
image
image

**Comment by klutchell** [comment]
LGTM

**Pull request merged**
