### PR TITLE
ci: Add needs to custom composite actions

### PR DESCRIPTION
**Pull request by issenn**
Change-type: minor

### CODE REVIEW

**Comment by issenn** [comment]
Can `needs` be passed to action ?

Why can't uses the fork repository as a reusable workflow ?
Like this `uses: issenn/flowzone/.github/workflows/flowzone.yml@v0.54.0` will got an `workflow not found` error.

**Comment by ab77** [comment]
> Can `needs` be passed to custom composite action ?

@klutchell do you recall why we didn't set `restrict_custom_actions: true` here already? For the other part, I don't see any issues passing the `needs` object to custom actions...

> Why can't uses the fork repository as a reusable workflow ? Like this `uses: issenn/flowzone/.github/workflows/flowzone.yml@v0.54.0` will got an `workflow not found` error.

@issenn that should work - did you check your repo/org settings to see if reusable workflows are enabled/unrestricted?

**Comment by issenn** [comment]
> > Why can't uses the fork repository as a reusable workflow ? Like this `uses: issenn/flowzone/.github/workflows/flowzone.yml@v0.54.0` will got an `workflow not found` error.
> 
> @issenn that should work - did you check your repo/org settings to see if reusable workflows are enabled/unrestricted?

I can't find related options in repo settings, only see `Allow all actions and reusable workflows` enabled in `Settings`-`Action`-`General`-`Actions permissions`. I didn't change any settings, I'll try again later with fork repository.


> except adding a new input at this point would break any existing custom actions that aren't expecting it. Might be better to find a way to do it with env vars like we did for custom matrix, etc.

I think, adding a new input element in the action does not affect other actions, because this element is unused. `needs` has some pre-initialized `event_types` and `project_types`, and `env.matrix_value` can only pass matrix strategy parameters.

**Comment by klutchell** [comment]
Hey @issenn , do you still need this change? Would you mind updating your PR to use the change I suggested above to avoid breaking existing workflows?
```
echo "needs_json=${{ toJSON(needs) }}" >> $GITHUB_ENV
```

**Pull request closed without merging**
