### PR TITLE
Install custom Wrangler version & show command output

### PR DESCRIPTION
**Pull request by vipulgupta2048**
More clarity on why the Cloudflare command failed. Currently even the errors are piped into the summary. 

This adds output logs to both the action run and flowzone summary.

Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>

### CODE REVIEW

**Comment by ab77** [comment]
> More clarity on why the Cloudflare command failed. Currently even the errors are piped into the summary.
> 
> This adds output logs to both the action run and flowzone summary.

Consider also https://balena.zulipchat.com/#narrow/stream/348930-balena-io.2Fflowzone/topic/request.20to.20the.20Cloudflare.20API.20failed/near/338666092

**Comment by klutchell** [comment]
lgtm

**Comment by vipulgupta2048** [comment]
Will use this PR to do the wrangler install command as discussed

**Comment by vipulgupta2048** [comment]
Found a way to install latest Wrangler version using the same action.

**Comment by vipulgupta2048** [comment]
@balena-ci I self-certify!

**Comment by vipulgupta2048** [comment]
Screenshot from 2023-03-01 12-23-21

**Pull request merged**
