### PR TITLE
Add Dockerfile parameter

### PR DESCRIPTION
**Pull request by ab77**
Change-type: patch

### CODE REVIEW

**Comment by ab77** [comment]
@balena-ci I self-certify!

**Comment by klutchell** [comment]
@ab77 I was trying to avoid extra inputs like this as inputs are an arbitrary interface that is easy to break.

In a previous [commit ](https://github.com/product-os/flowzone/pull/145/commits/5af10a8a4a07017d739eb1fc33545ce9a349e5c1)I removed this input and [replaced it with support for docker bake files](https://github.com/product-os/flowzone/pull/155).

We should remove this input, or note on the README that it is ignored if using docker bake files.

**Comment by ab77** [comment]
OK I see, I'll revert this then cc @pipex @cywang117 @Page-

**Comment by ab77** [comment]
reverted in https://github.com/product-os/flowzone/pull/205

**Pull request merged**
