### PR TITLE
Add npm_test_command as an option for changing the npm test command

### PR DESCRIPTION
**Pull request by thgreasi**
Change-type: minor
Signed-off-by: Thodoris Greasidis <thodoris@balena.io>

### CODE REVIEW

**Comment by klutchell** [comment]
IMO we should avoid adding new inputs for every edge case. As soon as a new input is used we can never change or remove it without breaking repos.

What is the use case here? Why can't the behaviour of npm test be changed? Or why not use a custom test stage as documented on the readme?

**Comment by thgreasi** [comment]
This will help migrating the SDK tests sooner than later b/c atm I would need a way to provide a set of different user credentials for each node version, and atm I can't do such a thing.
The short term solution I came up with was adding this to disable the default node tests and add a custom test workflow in the SDK that reads the repo's secrets and starts the tests with those injected.

I heard that the current workaround w/o this is to set `"test": "echo 'Skipping'"` in the package.json, which I didn't really love.

**Comment by klutchell** [comment]
I think adding a fake test to the sdk to avoid failing jobs is preferable
to adding a feature to Flowzone that shouldn't really be required and will
have to be maintained indefinitely.

**Comment by thgreasi** [comment]
> I think adding a fake test to the sdk to avoid failing jobs

In that case it might make sense to wait until flowzone adds support for injecting repo secrets to the test runners, so that `npm test` still does the expected thing.

**Comment by Page-** [comment]
I completely agree with @klutchell here @thgreasi, this command is only desired as a way to have `npm test` but not have flowzone use it which is very specialized to the current SDK needs

**Pull request closed without merging**
