### PR TITLE
patch: Add flowzone Docs website

### PR DESCRIPTION
**Pull request by vipulgupta2048**
Add Flowzone website using defaults only

Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>

### CODE REVIEW

**Comment by ab77** [comment]
@vipulgupta2048 I fixed the link for you, so now it's over to you to debug the website build:
https://github.com/product-os/flowzone/actions/runs/3661771730/jobs/6190322259#step:7:46

Maybe the link needs to be moved to `docs/README.md`, I am not sure..

**Comment by vipulgupta2048** [comment]
Oh very nice one, thanks! I tested without a working directory change and it's fine now. The error that we were seeing was due the README.md not able to find the image `logo.png`, we kept it configured to be strict about broken links. 

That's the reason why the build still throws an error in Flowzone if you see now but doesn't break it: flowzone.pages.dev

**Comment by vipulgupta2048** [comment]
@balena-ci I self-certify

**Comment by vipulgupta2048** [comment]
@balena-ci I self-certify!

**Pull request merged**
