### PR TITLE
Adds patch bump to commit footer on e2e

### PR DESCRIPTION
**Pull request by otaviojacobi**
Change-type: patch

### CODE REVIEW

**Comment by klutchell** [comment]
@otaviojacobi you can test this by running the e2e workflow on your python-sdk repo, but in the workflow command line add `--ref otaviojacobi/adds-patch-change-to-footer` so the workflow itself uses this branch of `e2e.yml`.

**Comment by otaviojacobi** [comment]
> @otaviojacobi you can test this by running the e2e workflow on your python-sdk repo, but in the workflow command line add `--ref otaviojacobi/adds-patch-change-to-footer` so the workflow itself uses this branch of `e2e.yml`.

@klutchell I will do that next week, for the time being I can test because I did some small fix on the sdk repo versionist file to support patch: etc

**Comment by otaviojacobi** [comment]
Seems to work, please see: https://github.com/balena-io/balena-sdk-python/pull/305/commits

**Comment by klutchell** [comment]
lgtm

**Pull request merged**
