### PR TITLE
Add yaml header to repo.yml

### PR DESCRIPTION
**Pull request by vpnarea**
This is a test to see if external contributors can modify files outside of `.github/`.

### CODE REVIEW

**Comment by ab77** [comment]
getting [closer](https://github.com/product-os/flowzone/actions/runs/3587102694/jobs/6037111708#step:5:39)

**Comment by klutchell** [comment]
> getting [closer](https://github.com/product-os/flowzone/actions/runs/3587102694/jobs/6037111708#step:5:39), if it works, [balena-io/deploy-to-balena-action#234](https://github.com/balena-io/deploy-to-balena-action/pull/234) should fix it @klutchell cc @20k-ultra

I was about open an issue for this but I see @ab77 is all over it!

**Comment by vpnarea** [comment]
> > getting [closer](https://github.com/product-os/flowzone/actions/runs/3587102694/jobs/6037111708#step:5:39), if it works, [balena-io/deploy-to-balena-action#234](https://github.com/balena-io/deploy-to-balena-action/pull/234) should fix it @klutchell cc @20k-ultra
> 
> I was about open an issue for this but I see @ab77 is all over it!

Give my TS is a bit lacking, if anyone can massage my "fix" to pass tests, that would be awesome!

**Comment by ab77** [comment]
@20k-ultra thank you!

@klutchell well, it worked - we can probably merge it now to complete the test...

**Review by klutchell — APPROVED** [review]

**Pull request merged**
